# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 895ebb389825c29bd4e0addcf7579d6c69d199cc # frozen: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 0a0b7a830386ba6a31c2ec8316849ae4d1b8240d # frozen: 6.0.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/tconbeer/sqlfmt
    rev: 07e326fc2d2acf4f5a041397717f17db6b66af79 # frozen: v0.26.0
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: ['.[jinjafmt]']
        args: [--line-length=99]

  - repo: https://github.com/google/yamlfmt
    rev: ac76bb931851dda64a55ef746ca9b8bb41634b98 # frozen: v0.16.0
    hooks:
      - id: yamlfmt
        args: [-conf, .yamlfmt]
