# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 25a8c8da6c24a3b9a1a536e2674683dd0eead5d6 # frozen: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: c8ab4a5b21bac924d106e3103dd7c979fdd0f9bc # frozen: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/tconbeer/sqlfmt
    rev: 07e326fc2d2acf4f5a041397717f17db6b66af79 # frozen: v0.26.0
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: ['.[jinjafmt]']
        args: [--line-length=99]

  - repo: https://github.com/google/yamlfmt
    rev: ac76bb931851dda64a55ef746ca9b8bb41634b98 # frozen: v0.16.0
    hooks:
      - id: yamlfmt
        args: [-conf, .yamlfmt]
