name: CI_pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  CI_jobs:
    runs-on: self-hosted # ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.2
        with:
          version: "0.5.28"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

      - name: Run isort
        run: uv run isort --check --diff ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run yamllint
        run: uv run yamllint -c .yamllint ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run sqlfmt
        run: uv run sqlfmt --diff ${{ steps.changed-files.outputs.all_changed_files }} -l 99
